[package]
name = "rim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.0"
futures = "0.3.28"
# TODO: not "full"
tokio = { version = "1", features = ["full"] }
